import Head from 'next/head';
import { Inter } from 'next/font/google';
import { AppShell, Container, Header } from '@mantine/core';
import Logo from '@/shared/ui/Logo';
import { AppNavbar } from '@/widgets/navbar/';
import { Folder } from '@/widgets/folder';
import { DashboardFolderList } from '@/widgets/dashboard-folder-list/ui/DashboardFolderList';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        padding="md"
        navbar={<AppNavbar />}
        header={
          <Header height={60} p="xs" px="xl">
            <Logo />
            {/* Header content */}
          </Header>
        }
      >
        <Container>
          <DashboardFolderList />
        </Container>
      </AppShell>
    </>
  );
}
